services:
  # Nginx
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./test/localhost/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./test/localhost/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ddd-sample-system
  # API 服務
  ddd-sample-system:
    container_name: ddd-sample-system
    build:
      context: .
      args:
        APP_CMD: system
    ports: 
      - 7000:7000
    environment:
      PROJECT_NAME: ddd-sample
      PROJECT_ENV: local
      CONFIG_PATH: /go/src/ddd-sample
      # account db
      DB_ACCOUNT_ADDR: local-db:3306
      DB_ACCOUNT_USER: root
      DB_ACCOUNT_PASS: 1234
    restart: always
    depends_on:
      - local-db
    command:
      - /go/src/ddd-sample/app
  # 資料庫
  local-db:
    container_name: local-db
    image: mysql:8.0.36
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "./test/localhost/mysql/auth_schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./test/localhost/mysql/auth_data.sql:/docker-entrypoint-initdb.d/2.sql"